### ISSUE TITLE
Quick usage example

### ISSUE THREAD

**Issue by mrhanky17** [vovanbo/aiohttp_json_api#8]
Hi,
I'm interessted in using this library but I'm not sure how to use this one. 
I've setup a SQLAlchemy models, a quick example in the usage would be very nice. :)

**Comment by vovanbo** [comment]
Hi!

Example application is one of things to do in this project. May be at this weekend I will pay attention for some examples. At this moment, i use aiohttp-json-api with aiopg and **SQLAlchemy Core** (models based on [attrs](http://www.attrs.org/en/stable/) package).

This project in active development, and breaking changes can occurred at any time.

First priority is significant increase of test coverage now. At early stages of development tests are better than any docs. And, I hope tests will require some basic apps based on this package.

Thank you for interest. I will notice you about any changes related to usage examples.

**Comment by vovanbo** [comment]
@mrhanky17 Hi! Excuse me for some delay. Look at simple example added to repo. Link is here: https://github.com/vovanbo/aiohttp_json_api/tree/master/examples/simple
